### ISSUE TITLE
小黑盒签到失败

### ISSUE THREAD

**Issue by Cytuslcy** [clover1420/AutoSign#10]
2023/3/25开始小黑盒提示
![image](https://user-images.githubusercontent.com/60951374/228752621-7baa0b2b-2c45-4036-b138-b8bbeb0f36ce.png)

可能是API上的盒该更新版本了，部分API开始禁止1.3.235版本调用了

**Comment by clover1420** [comment]
小黑盒更新了key算法，暂时签到无法获得奖励。
