### ISSUE TITLE
小黑盒签到失败

### ISSUE THREAD

**Issue by ichensw** [clover1420/AutoSign#11]
小黑盒:您的应用版本过低，请升级到最新版本获取奖励

应用版本v1.3.262。

**Comment by clover1420** [comment]
小黑盒更新了key算法，暂时签到无法获得奖励。

**Comment by wonderhong** [comment]
> 小黑盒更新了key算法，暂时签到无法获得奖励。

现在只签到但是不能获得奖励欸，并且分享任务也没做
