### ISSUE TITLE
请问能做个企业微信机器人的推送吗

### ISSUE THREAD

**Issue by sunnyhmz7010** [clover1420/AutoSign#15]
[群机器人配置说明](https://developer.work.weixin.qq.com/document/path/91770)

**Comment by clover1420** [comment]
推送你不是有企业微信推送吗。

**Comment by sunnyhmz7010** [comment]
那个是企业微信应用，现在创要可信ip没法用了，我说的是企业微信群机器人webhook推送

**Comment by clover1420** [comment]
好的，等下研究一下。

**Comment by clover1420** [comment]
已经添加了，你重新拉取下代码试试。
