### ISSUE TITLE
小黑盒

### ISSUE THREAD

**Issue by js3497** [clover1420/AutoSign#21]
请问小黑盒目前还能用嘛，我这里的返回一直是
{'status': 'failed', 'msg': '验证参数错误,CODE:9', 'version': '1.0', 'result': {}}
报错信息
小黑盒:出现了错误,错误信息'links'

**Comment by clover1420** [comment]
小黑盒的目前用不了了

**Comment by clover1420** [comment]
小黑盒的目前用不了了
