### ISSUE TITLE
求助，10054

### ISSUE THREAD

**Issue by MikasaEureka** [clover1420/AutoSign#3]
![image](https://user-images.githubusercontent.com/37149207/180475737-74f5675a-dceb-4d45-b84f-a31b5cf4c448.png)
这个是什么原因呢

**Comment by clover1420** [comment]
这可能你网络问题，换个网络试试看。

**Comment by MikasaEureka** [comment]
我尝试把我电脑上的退了，然后最后好了，可能也和网络有关系吧，，，，
